name: tubes_promvis_kelompok_8
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_hooks: ^0.18.6
  flutter_localizations:
    sdk: flutter
  go_router: ^7.0.2
  graphql_flutter: ^5.1.2
  nhost_dart: ^1.0.0
  nhost_flutter_graphql: ^3.0.0
  shared_preferences: ^2.1.1
  talker_flutter: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  go_router_builder: ^2.0.0
  build_runner: ^2.0.0
  build_verify: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
